### ISSUE TITLE
Error: Call to undefined method Redis::transaction()

### ISSUE THREAD

**Issue by yocmen** [tillkruss/laravel-phpredis#10]
Hi, i have this problem in L5.1, i get this error from queues:

`vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php in line 181 - Call to undefined method Redis::transaction()`

i changed the Alias in app.php to `'LRedis'    => 'Illuminate\Support\Facades\Redis',`

Any one can help me please?

**Comment by tillkruss** [comment]
Upgrade to 5.4. It support PhpRedis out of the box much better than this package.

**Comment by yocmen** [comment]
i cant upgrade, my system is too big with a lot of custom packages, but i cant find why im getting this error for the queues with redis...

**Comment by tillkruss** [comment]
Sorry, I know 5.1 is LTS, but I don't want to provide free support for this package anymore.

Your error message kinda sounds like your PhpRedis version doesn't support transactions. Just a guess.
