### ISSUE TITLE
Call to undefined method Redis::transaction()

### ISSUE THREAD

**Issue by zhangqm666** [tillkruss/laravel-phpredis#11]
Hello,
I can't start queue jobs after I replace the default redis service provider to TillKruss\LaravelPhpRedis\RedisServiceProvider::class in laravel 5.1.  When I run " php artisan queue:work redis --sleep=3 --tries=3 --daemon" it says "PHP Fatal error:  Call to undefined method Redis::transaction() in /data/web/project/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php on line 181".

**Comment by tillkruss** [comment]
Try upgrading your PhpRedis extension to the latest version.

**Comment by tillkruss** [comment]
If you can upgrade Laravel to 5.5, it handles PhpRedis internally and much better than this package.
