### ISSUE TITLE
Can this be used with 5.1?

### ISSUE THREAD

**Issue by bicatu** [tillkruss/laravel-phpredis#3]
Since 5.1 is the LTS I'd like to give it a try for your package.

I see "illuminate/cache": "~5.2" and "illuminate/redis": "~5.2" so I wonder if or what could be the changes to make this work with 5.1.

**Comment by tillkruss** [comment]
Those are only dev requirements. You should be able to install and use the package.

If it doesn't work, feel free to submit a PR for 5.1 compatibility.

**Comment by bicatu** [comment]
Thank you. It worked.  I tried even with Lumen though I had to override the Application to make it not call the registerRedisBinding.

Do you have a Slack channel for discussion in general?

**Comment by tillkruss** [comment]
How about right here?

**Comment by tillkruss** [comment]
@bicatu I just a Lumen support. Let me know if it works for you.
