### ISSUE TITLE
Class \Illuminate\Redis\Database not found

### ISSUE THREAD

**Issue by kickthemooon** [tillkruss/laravel-phpredis#7]
Me and my friend have a strange issue.
We want to update laravel to 5.4.
I updated and everything works as expected BUT
on my friends machine we get a fatal error exception:

```
FatalErrorException in ...\vendor\tillkruss\laravel-phpredis\src\Database.php line 10:Class 'Illuminate\Redis\Database' not found

in Database.php line 10
```

We are not sure why this would be happening.
In 5.4 it is really missing but on my machine all works...

**Comment by tillkruss** [comment]
This package isn't needed in 5.4 anymore. We've added full support for PhpRedis.
