### ISSUE TITLE
how to interact with redis

### ISSUE THREAD

**Issue by ctf0** [tillkruss/laravel-phpredis#8]
its kinda dump, but how to interact with redis on lara v5.3 ?
i've followed the steps but when trying to 
```php
\Redis::publish('all-channel', json_encode($data));
```
i get an error
```
Non-static method Redis::publish() cannot be called statically
```

**Comment by tillkruss** [comment]
Make sure you import the full Redis facade namespace, not the short single word.

**Comment by ctf0** [comment]
okay, can u please tell me the namespace for it ?
